Class PEX.MyOutboundAdapter Extends Grongier.PEX.OutboundAdapter [ GeneratedBy = Grongier.PEX.Utils ]
{

Property %classname As %String [ InitialExpression = "MyOutboundAdapter", Internal ];

/// One or more Classpaths (separated by '|' character) needed in addition to the ones configured in the Remote Gateway
Property %classpaths As %String(MAXLEN = "") [ InitialExpression = "/irisdev/app/src/python/demo/" ];

Property %module As %String [ InitialExpression = "MyOutboundAdapter", Internal ];

Method SetPropertyValues()
{
	quit
}

}
