ARG BASE=intersystemsdc/iris-community
FROM $BASE

COPY --chown=irisowner:irisowner . /irisdev/app

WORKDIR /irisdev/app

## Python stuff
ARG IRISUSERNAME
ARG IRISPASSWORD
ENV IRISUSERNAME=${IRISUSERNAME}
ENV IRISPASSWORD=${IRISPASSWORD}
ENV IRISNAMESPACE="IRISAPP"
ENV PYTHON_PATH=/usr/irissys/bin/
ENV PIP_BREAK_SYSTEM_PACKAGES=1
ENV LD_LIBRARY_PATH=${ISC_PACKAGE_INSTALLDIR}/bin
ENV PATH="/home/irisowner/.local/bin:/usr/irissys/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/irisowner/bin"

RUN pip install build
RUN python3 -m build --wheel
RUN WHEEL=$(find dist -name '*.whl' -print -quit) && \
    pip install --force-reinstall "${WHEEL}[dev]"

ENTRYPOINT [ "/irisdev/app/test-in-docker.sh" ]
