site_name: IoP (Interoperability On Python)
site_description: A Python-first approach to build Interoperability solutions on IRIS and Health Connect
site_author: grongier@intersystems.com 
site_url: https://grongierisc.github.io/interoperability-embedded-python/
docs_dir: docs
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - First Steps: getting-started/first-steps.md
    - Register Component: getting-started/register-component.md
  - API documentation:
    - Command Line Interface: command-line.md
    - Python API: python-api.md
  - DTL Support: dtl.md
  - Logging: logging.md
  - Debugging: debug.md
  - Production Settings: prod-settings.md
  - Contributing:
    - Contributing: contributing.md
    - Code of Conduct: code-of-conduct.md
  - Reference:
    - Examples: example.md
    - Useful Links: useful-links.md
  - About:
    - Changelog: changelog.md
    - Credits: credits.md
    - Benchmarks: benchmarks.md

theme: readthedocs

markdown_extensions:
- pymdownx.snippets