site_name: IoP (Interoperability On Python)
site_description: A Python-first approach to build Interoperability solutions on IRIS and Health Connect
site_author: grongier@intersystems.com 
site_url: https://grongierisc.github.io/interoperability-embedded-python/
docs_dir: docs
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - First Steps: getting-started/first-steps.md
    - Register Component: getting-started/register-component.md
  - API documentation:
    - Command Line Interface: command-line.md
    - Python API: python-api.md
  - Reference:
    - Examples: example.md
    - Useful Links: useful-links.md

theme: readthedocs