Class PEX.Bench.MSG Extends Ens.Request
{

Property PropertyName0 As %String;

Property PropertyName1 As %String;

Property PropertyName2 As %String;

Property PropertyName3 As %String;

Property PropertyName4 As %String;

Property PropertyName5 As %String;

Property PropertyName6 As %String;

Property PropertyName7 As %String;

Property PropertyName8 As %String;

Property PropertyName9 As %String;

Storage Default
{
<Data name="MSGDefaultData">
<Subscript>"MSG"</Subscript>
<Value name="1">
<Value>PropertyName0</Value>
</Value>
<Value name="2">
<Value>PropertyName1</Value>
</Value>
<Value name="3">
<Value>PropertyName2</Value>
</Value>
<Value name="4">
<Value>PropertyName3</Value>
</Value>
<Value name="5">
<Value>PropertyName4</Value>
</Value>
<Value name="6">
<Value>PropertyName5</Value>
</Value>
<Value name="7">
<Value>PropertyName6</Value>
</Value>
<Value name="8">
<Value>PropertyName7</Value>
</Value>
<Value name="9">
<Value>PropertyName8</Value>
</Value>
<Value name="10">
<Value>PropertyName9</Value>
</Value>
</Data>
<DefaultData>MSGDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
