name: IRIS preview

on:
  # schedule:
  #   - cron: "17 3 * * *"
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      IMAGE: intersystemsdc/iris-community:preview
    steps:
      - uses: actions/checkout@v5
      - run: docker pull "$IMAGE"
      - run: |
          docker build --build-arg BASE="$IMAGE" \
            --build-arg IRISUSERNAME=${{ secrets.IRIS_USERNAME || 'SuperUser' }} \
            --build-arg IRISPASSWORD=${{ secrets.IRIS_PASSWORD || 'SYS' }} \
            -t pytest-iris-preview -f dockerfile-ci .
          docker run -i --rm pytest-iris-preview
